from container import LiquidContainer


def main():
    print("Press enter to continue in the story.")
    input()
    b = input("Big coffee cup name and volume: ")
    b = b.split("/")
    big = LiquidContainer(b[0], float(b[1]), False)

    s = input("Small coffee cup name and volume: ")
    s = s.split("/")
    small = LiquidContainer(s[0], float(s[1]), False)

    j = input("Coffee jug name and volume: ")
    j = j.split("/")
    jug = LiquidContainer(j[0], float(j[1]), True)

    print("Created the following containers:")
    print(big)
    print(small)
    print(jug)
    input()
    print("Filling {}...".format(jug.get_name()))
    jug.fill()
    print("Jug status after filling:")
    print(jug)
    input()
    amount_to_be_served = float(input("How many litres of coffee should be served?\n"))
    print("Trying to pour {} litres from {} into {} and {}".format(amount_to_be_served, jug.get_name(),
                                                                   big.get_name(), small.get_name()))

    print("Managed to pour {} litres to {}".format(jug.pour_to_another(big, amount_to_be_served), big.get_name()))
    print("Managed to pour {} litres to {}".format(jug.pour_to_another(small, amount_to_be_served), small.get_name()))
    input()
    print("Cup and jug statuses after pouring:")
    print(big)
    print(small)
    print(jug)
    input()
    if big.get_liquid_volume() == small.get_liquid_volume():
        print("Both were happy for having the same amount of coffee and lived happily everafter.")
    else:
        if big.get_liquid_volume() > small.get_liquid_volume():
            print("The holder of {} became angry for having less coffee and flipped their "
                  "coffee cup!".format(small.get_name()))
            print("All of their coffee poured out:")
            small.flip()
            print(small)
            input()
            print("They also flipped the jug!")
            jug.flip()
            print("However, it had a lid, so the liquid stayed inside:")
            print(jug)
            input()
            print("So they had to force flip to the jug!")
            jug.force_flip()
            print("Now it's empty and no longer has a lid:")
            print(jug)
            input()
            print("Next they got mad and nicked all the coffee they could from {}".format(big.get_name()))
            small.fill_from(big)
            print("{} litres were stolen.".format(small.get_liquid_volume()))
            input()
            print("Cup statuses after the theft:")
            print(big)
            print(small)
            input()
            print("Now finally the holder of {} can drink their coffee:".format(small.get_name()))
            small.flip()
            print(small)
        else:
            print("The holder of {} became angry for having less coffee and "
                  "flipped their coffee cup!".format(big.get_name()))
            print("All of their coffee poured out:")
            big.flip()
            print(big)
            input()
            print("They also flipped the jug!")
            jug.flip()
            print("However, it had a lid, so the liquid stayed inside:")
            print(jug)
            input()
            print("So they had to force flip to the jug!")
            jug.force_flip()
            print("Now it's empty and no longer has a lid:")
            print(jug)
            input()
            print("Next they got mad and nicked all the coffee they could from {}".format(small.get_name()))
            big.fill_from(small)
            print("{} litres were stolen.".format(big.get_liquid_volume()))
            input()
            print("Cup statuses after the theft:")
            print(big)
            print(small)
            input()
            print("Now finally the holder of {} can drink their coffee:".format(big.get_name()))
            big.flip()
            print(big)


main()
